/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package s3tobigquery

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun dummyTest() {
        val test = ""
        assertNotNull(test, "test shoud not be null")
    }
}
